"""
既存のパレット在庫を残したまま、自由入力の商品名に対応する。

・pallet_inventory / pallet_receiving_plans に商品名保存列を追加
・商品マスター未登録でも item_id=NULL で登録可能にする
・既存行の商品名は items.name から引き継ぐ
・既存の在庫数、履歴、QRコード、IDは維持する

何度実行しても同じ状態になる安全な移行スクリプト。
"""

from database import get_connection
from pages.pallet.pallet_tables import (
    is_postgres_connection,
    validate_pallet_database,
)


CONNECTION_ATTRIBUTES = (
    "_conn",
    "conn",
    "_connection",
    "connection",
    "_raw_conn",
    "raw_conn",
    "_raw_connection",
    "raw_connection",
)


POSTGRES_RECEIVING_TABLE = """
CREATE TABLE IF NOT EXISTS pallet_receiving_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_code TEXT NOT NULL UNIQUE,
    receiving_date DATE NOT NULL,
    company_id INTEGER NOT NULL,
    project_id INTEGER,
    item_id INTEGER,
    item_name TEXT NOT NULL,
    pallet_count INTEGER NOT NULL,
    qty_per_pallet INTEGER NOT NULL,
    total_qty INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT '入庫待ち',
    batch_code TEXT UNIQUE,
    remarks TEXT,
    created_by TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed_by TEXT,
    confirmed_at TIMESTAMPTZ,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT pallet_receiving_plans_company_fkey
        FOREIGN KEY (company_id) REFERENCES companies(id),
    CONSTRAINT pallet_receiving_plans_project_fkey
        FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT pallet_receiving_plans_item_fkey
        FOREIGN KEY (item_id) REFERENCES items(id),
    CHECK (pallet_count >= 1),
    CHECK (qty_per_pallet >= 1),
    CHECK (total_qty = pallet_count * qty_per_pallet),
    CHECK (status IN ('入庫待ち', '入庫済み', '取消'))
)
"""


SQLITE_INVENTORY_TABLE = """
CREATE TABLE {table_name} (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pallet_code TEXT NOT NULL UNIQUE,
    batch_code TEXT NOT NULL,
    pallet_sequence INTEGER NOT NULL,
    total_pallets INTEGER NOT NULL,
    company_id INTEGER NOT NULL,
    project_id INTEGER,
    item_id INTEGER,
    item_name TEXT NOT NULL,
    initial_qty INTEGER NOT NULL,
    current_qty INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT '保管中',
    location TEXT,
    remarks TEXT,
    created_by TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (item_id) REFERENCES items(id),
    UNIQUE (batch_code, pallet_sequence),
    CHECK (pallet_sequence >= 1),
    CHECK (total_pallets >= 1),
    CHECK (pallet_sequence <= total_pallets),
    CHECK (initial_qty >= 0),
    CHECK (current_qty >= 0),
    CHECK (current_qty <= initial_qty),
    CHECK (status IN ('保管中', '出庫済み'))
)
"""


SQLITE_RECEIVING_TABLE = """
CREATE TABLE {table_name} (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    receipt_code TEXT NOT NULL UNIQUE,
    receiving_date TEXT NOT NULL,
    company_id INTEGER NOT NULL,
    project_id INTEGER,
    item_id INTEGER,
    item_name TEXT NOT NULL,
    pallet_count INTEGER NOT NULL,
    qty_per_pallet INTEGER NOT NULL,
    total_qty INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT '入庫待ち',
    batch_code TEXT UNIQUE,
    remarks TEXT,
    created_by TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed_by TEXT,
    confirmed_at TEXT,
    is_deleted INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (item_id) REFERENCES items(id),
    CHECK (pallet_count >= 1),
    CHECK (qty_per_pallet >= 1),
    CHECK (total_qty = pallet_count * qty_per_pallet),
    CHECK (status IN ('入庫待ち', '入庫済み', '取消'))
)
"""


INDEX_STATEMENTS = (
    """
    CREATE INDEX IF NOT EXISTS idx_pallet_inventory_batch_code
    ON pallet_inventory (batch_code)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_pallet_inventory_item_status
    ON pallet_inventory (item_id, status)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_pallet_inventory_company
    ON pallet_inventory (company_id)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_pallet_history_pallet_created
    ON pallet_history (pallet_id, created_at)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_pallet_receiving_status_date
    ON pallet_receiving_plans (status, receiving_date)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_pallet_receiving_company
    ON pallet_receiving_plans (company_id)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_pallet_receiving_item
    ON pallet_receiving_plans (item_id)
    """,
)


def rollback_safely(conn):
    candidates = [conn]
    seen = set()

    while candidates:
        candidate = candidates.pop(0)

        if id(candidate) in seen:
            continue

        seen.add(id(candidate))
        rollback = getattr(candidate, "rollback", None)

        if callable(rollback):
            try:
                rollback()
            except Exception:
                pass
            return

        for attribute in CONNECTION_ATTRIBUTES:
            try:
                wrapped = getattr(candidate, attribute)
            except (AttributeError, TypeError):
                continue

            if wrapped is not None and wrapped is not candidate:
                candidates.append(wrapped)


def _sqlite_columns(conn, table_name):
    rows = conn.execute(f"PRAGMA table_info({table_name})").fetchall()
    columns = {}

    for row in rows:
        try:
            name = str(row["name"])
            not_null = int(row["notnull"] or 0)
        except (KeyError, IndexError, TypeError):
            name = str(row[1])
            not_null = int(row[3] or 0)

        columns[name] = {"not_null": not_null}

    return columns


def _sqlite_table_exists(conn, table_name):
    row = conn.execute(
        """
        SELECT COUNT(*)
        FROM sqlite_master
        WHERE type = 'table' AND name = ?
        """,
        (table_name,),
    ).fetchone()

    try:
        return int(row[0]) == 1
    except (KeyError, IndexError, TypeError):
        return int(next(iter(row.values()))) == 1


def _sqlite_name_expression(table_name, columns):
    if "item_name" in columns:
        return (
            f"COALESCE(NULLIF(TRIM({table_name}.item_name), ''), "
            f"(SELECT name FROM items WHERE id = {table_name}.item_id), "
            "'名称未設定')"
        )

    return (
        f"COALESCE((SELECT name FROM items "
        f"WHERE id = {table_name}.item_id), '名称未設定')"
    )


def _rebuild_sqlite_inventory(conn):
    columns = _sqlite_columns(conn, "pallet_inventory")
    needs_rebuild = (
        "item_name" not in columns
        or columns.get("item_id", {}).get("not_null") == 1
    )

    if not needs_rebuild:
        conn.execute(
            """
            UPDATE pallet_inventory
            SET item_name = COALESCE(
                NULLIF(TRIM(item_name), ''),
                (SELECT name FROM items WHERE id = pallet_inventory.item_id),
                '名称未設定'
            )
            """
        )
        return

    temporary_table = "pallet_inventory_free_name_new"
    conn.execute(f"DROP TABLE IF EXISTS {temporary_table}")
    conn.execute(
        SQLITE_INVENTORY_TABLE.format(table_name=temporary_table)
    )
    name_expression = _sqlite_name_expression(
        "pallet_inventory",
        columns,
    )
    conn.execute(
        f"""
        INSERT INTO {temporary_table} (
            id, pallet_code, batch_code, pallet_sequence, total_pallets,
            company_id, project_id, item_id, item_name,
            initial_qty, current_qty, status, location, remarks,
            created_by, created_at, updated_at, is_deleted
        )
        SELECT
            id, pallet_code, batch_code, pallet_sequence, total_pallets,
            company_id, project_id, item_id, {name_expression},
            initial_qty, current_qty, status, location, remarks,
            created_by, created_at, updated_at, is_deleted
        FROM pallet_inventory
        """
    )
    conn.execute("DROP TABLE pallet_inventory")
    conn.execute(
        f"ALTER TABLE {temporary_table} RENAME TO pallet_inventory"
    )


def _rebuild_sqlite_receiving(conn):
    if not _sqlite_table_exists(conn, "pallet_receiving_plans"):
        conn.execute(
            SQLITE_RECEIVING_TABLE.format(
                table_name="pallet_receiving_plans"
            )
        )
        return

    columns = _sqlite_columns(conn, "pallet_receiving_plans")
    needs_rebuild = (
        "item_name" not in columns
        or columns.get("item_id", {}).get("not_null") == 1
    )

    if not needs_rebuild:
        conn.execute(
            """
            UPDATE pallet_receiving_plans
            SET item_name = COALESCE(
                NULLIF(TRIM(item_name), ''),
                (SELECT name FROM items
                 WHERE id = pallet_receiving_plans.item_id),
                '名称未設定'
            )
            """
        )
        return

    temporary_table = "pallet_receiving_plans_free_name_new"
    conn.execute(f"DROP TABLE IF EXISTS {temporary_table}")
    conn.execute(
        SQLITE_RECEIVING_TABLE.format(table_name=temporary_table)
    )
    name_expression = _sqlite_name_expression(
        "pallet_receiving_plans",
        columns,
    )
    conn.execute(
        f"""
        INSERT INTO {temporary_table} (
            id, receipt_code, receiving_date, company_id, project_id,
            item_id, item_name, pallet_count, qty_per_pallet, total_qty,
            status, batch_code, remarks, created_by, created_at,
            updated_at, confirmed_by, confirmed_at, is_deleted
        )
        SELECT
            id, receipt_code, receiving_date, company_id, project_id,
            item_id, {name_expression}, pallet_count, qty_per_pallet,
            total_qty, status, batch_code, remarks, created_by, created_at,
            updated_at, confirmed_by, confirmed_at, is_deleted
        FROM pallet_receiving_plans
        """
    )
    conn.execute("DROP TABLE pallet_receiving_plans")
    conn.execute(
        f"ALTER TABLE {temporary_table} RENAME TO pallet_receiving_plans"
    )


def _install_sqlite(conn):
    conn.commit()
    conn.execute("PRAGMA foreign_keys = OFF")

    try:
        conn.execute("BEGIN")
        _rebuild_sqlite_inventory(conn)
        _rebuild_sqlite_receiving(conn)

        for statement in INDEX_STATEMENTS:
            conn.execute(statement)

        conn.commit()

    except Exception:
        rollback_safely(conn)
        raise

    finally:
        conn.execute("PRAGMA foreign_keys = ON")

    violations = conn.execute("PRAGMA foreign_key_check").fetchall()

    if violations:
        raise RuntimeError(
            "外部キー検証で不整合が見つかりました。"
            "移行前のDBバックアップを確認してください。"
        )


def _install_postgres(conn):
    conn.execute(POSTGRES_RECEIVING_TABLE)
    conn.execute(
        "ALTER TABLE pallet_inventory "
        "ADD COLUMN IF NOT EXISTS item_name TEXT"
    )
    conn.execute(
        "ALTER TABLE pallet_receiving_plans "
        "ADD COLUMN IF NOT EXISTS item_name TEXT"
    )
    conn.execute(
        """
        UPDATE pallet_inventory pi
        SET item_name = i.name
        FROM items i
        WHERE
            pi.item_id = i.id
            AND NULLIF(BTRIM(pi.item_name), '') IS NULL
        """
    )
    conn.execute(
        """
        UPDATE pallet_receiving_plans rp
        SET item_name = i.name
        FROM items i
        WHERE
            rp.item_id = i.id
            AND NULLIF(BTRIM(rp.item_name), '') IS NULL
        """
    )
    conn.execute(
        """
        UPDATE pallet_inventory
        SET item_name = '名称未設定'
        WHERE NULLIF(BTRIM(item_name), '') IS NULL
        """
    )
    conn.execute(
        """
        UPDATE pallet_receiving_plans
        SET item_name = '名称未設定'
        WHERE NULLIF(BTRIM(item_name), '') IS NULL
        """
    )
    conn.execute(
        "ALTER TABLE pallet_inventory "
        "ALTER COLUMN item_id DROP NOT NULL"
    )
    conn.execute(
        "ALTER TABLE pallet_receiving_plans "
        "ALTER COLUMN item_id DROP NOT NULL"
    )
    conn.execute(
        "ALTER TABLE pallet_inventory "
        "ALTER COLUMN item_name SET NOT NULL"
    )
    conn.execute(
        "ALTER TABLE pallet_receiving_plans "
        "ALTER COLUMN item_name SET NOT NULL"
    )

    for statement in INDEX_STATEMENTS:
        conn.execute(statement)


def install():
    conn = get_connection()
    postgres = is_postgres_connection(conn)
    database_name = "PostgreSQL / Supabase" if postgres else "SQLite"

    try:
        print(f"対象DB: {database_name}")

        if postgres:
            _install_postgres(conn)
            validate_pallet_database(conn)
            conn.commit()
        else:
            _install_sqlite(conn)
            validate_pallet_database(conn)

        print("商品名の直接入力対応が完了しました。")
        print("既存のパレット在庫・履歴・QRコード：維持OK")

    except Exception:
        rollback_safely(conn)
        raise

    finally:
        conn.close()


if __name__ == "__main__":
    install()
