"""
SHARK パレット管理テーブルの安全な再構築スクリプト。

対象は pallet_inventory / pallet_history /
pallet_receiving_plans の3テーブルだけ。
いずれかに1件でもデータがある場合は、削除せずに停止する。
"""

from database import get_connection
from pages.pallet.pallet_tables import (
    is_postgres_connection,
    validate_pallet_database,
)


TABLES = (
    "pallet_inventory",
    "pallet_history",
    "pallet_receiving_plans",
)
CONNECTION_ATTRIBUTES = (
    "_conn",
    "conn",
    "_connection",
    "connection",
    "_raw_conn",
    "raw_conn",
    "_raw_connection",
    "raw_connection",
)


POSTGRES_CREATE_STATEMENTS = (
    """
    CREATE TABLE pallet_inventory (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        pallet_code TEXT NOT NULL UNIQUE,
        batch_code TEXT NOT NULL,
        pallet_sequence INTEGER NOT NULL,
        total_pallets INTEGER NOT NULL,
        company_id INTEGER NOT NULL,
        project_id INTEGER,
        item_id INTEGER,
        item_name TEXT NOT NULL,
        initial_qty INTEGER NOT NULL,
        current_qty INTEGER NOT NULL,
        status TEXT NOT NULL DEFAULT '保管中',
        location TEXT,
        remarks TEXT,
        created_by TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
        CONSTRAINT pallet_inventory_company_fkey
            FOREIGN KEY (company_id) REFERENCES companies(id),
        CONSTRAINT pallet_inventory_project_fkey
            FOREIGN KEY (project_id) REFERENCES projects(id),
        CONSTRAINT pallet_inventory_item_fkey
            FOREIGN KEY (item_id) REFERENCES items(id),
        CONSTRAINT pallet_inventory_batch_sequence_key
            UNIQUE (batch_code, pallet_sequence),
        CHECK (pallet_sequence >= 1),
        CHECK (total_pallets >= 1),
        CHECK (pallet_sequence <= total_pallets),
        CHECK (initial_qty >= 0),
        CHECK (current_qty >= 0),
        CHECK (current_qty <= initial_qty),
        CHECK (status IN ('保管中', '出庫済み'))
    )
    """,
    """
    CREATE TABLE pallet_history (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        pallet_id BIGINT NOT NULL,
        pallet_code TEXT NOT NULL,
        history_type TEXT NOT NULL,
        qty INTEGER NOT NULL,
        before_qty INTEGER NOT NULL,
        after_qty INTEGER NOT NULL,
        username TEXT NOT NULL,
        remarks TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT pallet_history_pallet_id_fkey
            FOREIGN KEY (pallet_id) REFERENCES pallet_inventory(id),
        CHECK (history_type IN ('入庫', '出庫')),
        CHECK (qty >= 0),
        CHECK (before_qty >= 0),
        CHECK (after_qty >= 0)
    )
    """,
    """
    CREATE TABLE pallet_receiving_plans (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        receipt_code TEXT NOT NULL UNIQUE,
        receiving_date DATE NOT NULL,
        company_id INTEGER NOT NULL,
        project_id INTEGER,
        item_id INTEGER,
        item_name TEXT NOT NULL,
        pallet_count INTEGER NOT NULL,
        qty_per_pallet INTEGER NOT NULL,
        total_qty INTEGER NOT NULL,
        status TEXT NOT NULL DEFAULT '入庫待ち',
        batch_code TEXT UNIQUE,
        remarks TEXT,
        created_by TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        confirmed_by TEXT,
        confirmed_at TIMESTAMPTZ,
        is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
        CONSTRAINT pallet_receiving_plans_company_fkey
            FOREIGN KEY (company_id) REFERENCES companies(id),
        CONSTRAINT pallet_receiving_plans_project_fkey
            FOREIGN KEY (project_id) REFERENCES projects(id),
        CONSTRAINT pallet_receiving_plans_item_fkey
            FOREIGN KEY (item_id) REFERENCES items(id),
        CHECK (pallet_count >= 1),
        CHECK (qty_per_pallet >= 1),
        CHECK (total_qty = pallet_count * qty_per_pallet),
        CHECK (status IN ('入庫待ち', '入庫済み', '取消'))
    )
    """,
)


SQLITE_CREATE_STATEMENTS = (
    """
    CREATE TABLE pallet_inventory (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        pallet_code TEXT NOT NULL UNIQUE,
        batch_code TEXT NOT NULL,
        pallet_sequence INTEGER NOT NULL,
        total_pallets INTEGER NOT NULL,
        company_id INTEGER NOT NULL,
        project_id INTEGER,
        item_id INTEGER,
        item_name TEXT NOT NULL,
        initial_qty INTEGER NOT NULL,
        current_qty INTEGER NOT NULL,
        status TEXT NOT NULL DEFAULT '保管中',
        location TEXT,
        remarks TEXT,
        created_by TEXT NOT NULL,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        is_deleted INTEGER NOT NULL DEFAULT 0,
        FOREIGN KEY (company_id) REFERENCES companies(id),
        FOREIGN KEY (project_id) REFERENCES projects(id),
        FOREIGN KEY (item_id) REFERENCES items(id),
        UNIQUE (batch_code, pallet_sequence),
        CHECK (pallet_sequence >= 1),
        CHECK (total_pallets >= 1),
        CHECK (pallet_sequence <= total_pallets),
        CHECK (initial_qty >= 0),
        CHECK (current_qty >= 0),
        CHECK (current_qty <= initial_qty),
        CHECK (status IN ('保管中', '出庫済み'))
    )
    """,
    """
    CREATE TABLE pallet_history (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        pallet_id INTEGER NOT NULL,
        pallet_code TEXT NOT NULL,
        history_type TEXT NOT NULL,
        qty INTEGER NOT NULL,
        before_qty INTEGER NOT NULL,
        after_qty INTEGER NOT NULL,
        username TEXT NOT NULL,
        remarks TEXT,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (pallet_id) REFERENCES pallet_inventory(id),
        CHECK (history_type IN ('入庫', '出庫')),
        CHECK (qty >= 0),
        CHECK (before_qty >= 0),
        CHECK (after_qty >= 0)
    )
    """,
    """
    CREATE TABLE pallet_receiving_plans (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        receipt_code TEXT NOT NULL UNIQUE,
        receiving_date TEXT NOT NULL,
        company_id INTEGER NOT NULL,
        project_id INTEGER,
        item_id INTEGER,
        item_name TEXT NOT NULL,
        pallet_count INTEGER NOT NULL,
        qty_per_pallet INTEGER NOT NULL,
        total_qty INTEGER NOT NULL,
        status TEXT NOT NULL DEFAULT '入庫待ち',
        batch_code TEXT UNIQUE,
        remarks TEXT,
        created_by TEXT NOT NULL,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        confirmed_by TEXT,
        confirmed_at TEXT,
        is_deleted INTEGER NOT NULL DEFAULT 0,
        FOREIGN KEY (company_id) REFERENCES companies(id),
        FOREIGN KEY (project_id) REFERENCES projects(id),
        FOREIGN KEY (item_id) REFERENCES items(id),
        CHECK (pallet_count >= 1),
        CHECK (qty_per_pallet >= 1),
        CHECK (total_qty = pallet_count * qty_per_pallet),
        CHECK (status IN ('入庫待ち', '入庫済み', '取消'))
    )
    """,
)


INDEX_STATEMENTS = (
    """
    CREATE INDEX idx_pallet_inventory_batch_code
    ON pallet_inventory (batch_code)
    """,
    """
    CREATE INDEX idx_pallet_inventory_item_status
    ON pallet_inventory (item_id, status)
    """,
    """
    CREATE INDEX idx_pallet_inventory_company
    ON pallet_inventory (company_id)
    """,
    """
    CREATE INDEX idx_pallet_history_pallet_created
    ON pallet_history (pallet_id, created_at)
    """,
    """
    CREATE INDEX idx_pallet_receiving_status_date
    ON pallet_receiving_plans (status, receiving_date)
    """,
    """
    CREATE INDEX idx_pallet_receiving_company
    ON pallet_receiving_plans (company_id)
    """,
    """
    CREATE INDEX idx_pallet_receiving_item
    ON pallet_receiving_plans (item_id)
    """,
)


def row_value(row, key, index=0, default=None):
    if row is None:
        return default

    try:
        return row[key]
    except (KeyError, IndexError, TypeError):
        pass

    try:
        return row[index]
    except (KeyError, IndexError, TypeError):
        return default


def rollback_safely(conn):
    candidates = [conn]
    seen = set()

    while candidates:
        candidate = candidates.pop(0)

        if id(candidate) in seen:
            continue

        seen.add(id(candidate))
        rollback = getattr(candidate, "rollback", None)

        if callable(rollback):
            try:
                rollback()
            except Exception:
                pass
            return

        for attribute in CONNECTION_ATTRIBUTES:
            try:
                wrapped = getattr(candidate, attribute)
            except (AttributeError, TypeError):
                continue

            if wrapped is not None and wrapped is not candidate:
                candidates.append(wrapped)

    try:
        conn.execute("ROLLBACK")
    except Exception:
        pass


def table_exists(conn, table_name, postgres):
    if postgres:
        cursor = conn.execute(
            """
            SELECT COUNT(*) AS table_count
            FROM information_schema.tables
            WHERE
                table_schema = CURRENT_SCHEMA()
                AND table_name = %s
            """,
            (table_name,),
        )
    else:
        cursor = conn.execute(
            """
            SELECT COUNT(*) AS table_count
            FROM sqlite_master
            WHERE type = 'table' AND name = ?
            """,
            (table_name,),
        )

    row = cursor.fetchone()
    return int(row_value(row, "table_count", 0, 0) or 0) == 1


def table_count(conn, table_name, postgres):
    if not table_exists(conn, table_name, postgres):
        return 0

    cursor = conn.execute(f"SELECT COUNT(*) AS row_count FROM {table_name}")
    row = cursor.fetchone()
    return int(row_value(row, "row_count", 0, 0) or 0)


def rebuild():
    conn = get_connection()
    postgres = is_postgres_connection(conn)
    database_name = "PostgreSQL / Supabase" if postgres else "SQLite"

    try:
        counts = {
            table_name: table_count(conn, table_name, postgres)
            for table_name in TABLES
        }
        print(f"対象DB: {database_name}")

        for table_name, count in counts.items():
            print(f"現在件数: {table_name}={count}")

        if any(counts.values()):
            raise RuntimeError(
                "パレットデータまたは入庫予定が存在するため"
                "再構築を中止しました。データは変更されていません。"
            )

        conn.execute("DROP TABLE IF EXISTS pallet_receiving_plans")
        conn.execute("DROP TABLE IF EXISTS pallet_history")
        conn.execute("DROP TABLE IF EXISTS pallet_inventory")

        if postgres:
            conn.execute(
                "DROP SEQUENCE IF EXISTS pallet_receiving_plans_id_seq"
            )
            conn.execute("DROP SEQUENCE IF EXISTS pallet_history_id_seq")
            conn.execute("DROP SEQUENCE IF EXISTS pallet_inventory_id_seq")
            create_statements = POSTGRES_CREATE_STATEMENTS
        else:
            create_statements = SQLITE_CREATE_STATEMENTS

        for statement in create_statements:
            conn.execute(statement)

        for statement in INDEX_STATEMENTS:
            conn.execute(statement)

        validate_pallet_database(conn)
        conn.commit()
        print("パレット用テーブルの再構築が完了しました。")
        print("入庫予定・在庫・履歴・外部キー：確認OK")

    except Exception:
        rollback_safely(conn)
        raise

    finally:
        conn.close()


if __name__ == "__main__":
    rebuild()
