"""
SHARK パレット管理テーブルの安全な再構築スクリプト。

対象は pallet_inventory / pallet_history の2テーブルだけ。
どちらかに1件でもデータがある場合は、削除せずに停止する。
"""

from database import get_connection
from pages.pallet.pallet_tables import (
    is_postgres_connection,
    validate_pallet_database,
)


TABLES = ("pallet_inventory", "pallet_history")
CONNECTION_ATTRIBUTES = (
    "_conn",
    "conn",
    "_connection",
    "connection",
    "_raw_conn",
    "raw_conn",
    "_raw_connection",
    "raw_connection",
)


POSTGRES_CREATE_STATEMENTS = (
    """
    CREATE TABLE pallet_inventory (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        pallet_code TEXT NOT NULL UNIQUE,
        batch_code TEXT NOT NULL,
        pallet_sequence INTEGER NOT NULL,
        total_pallets INTEGER NOT NULL,
        company_id INTEGER NOT NULL,
        project_id INTEGER,
        item_id INTEGER NOT NULL,
        initial_qty INTEGER NOT NULL,
        current_qty INTEGER NOT NULL,
        status TEXT NOT NULL DEFAULT '保管中',
        location TEXT,
        remarks TEXT,
        created_by TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
        CONSTRAINT pallet_inventory_company_fkey
            FOREIGN KEY (company_id) REFERENCES companies(id),
        CONSTRAINT pallet_inventory_project_fkey
            FOREIGN KEY (project_id) REFERENCES projects(id),
        CONSTRAINT pallet_inventory_item_fkey
            FOREIGN KEY (item_id) REFERENCES items(id),
        CONSTRAINT pallet_inventory_batch_sequence_key
            UNIQUE (batch_code, pallet_sequence),
        CHECK (pallet_sequence >= 1),
        CHECK (total_pallets >= 1),
        CHECK (pallet_sequence <= total_pallets),
        CHECK (initial_qty >= 0),
        CHECK (current_qty >= 0),
        CHECK (current_qty <= initial_qty),
        CHECK (status IN ('保管中', '出庫済み'))
    )
    """,
    """
    CREATE TABLE pallet_history (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        pallet_id BIGINT NOT NULL,
        pallet_code TEXT NOT NULL,
        history_type TEXT NOT NULL,
        qty INTEGER NOT NULL,
        before_qty INTEGER NOT NULL,
        after_qty INTEGER NOT NULL,
        username TEXT NOT NULL,
        remarks TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT pallet_history_pallet_id_fkey
            FOREIGN KEY (pallet_id)
            REFERENCES pallet_inventory(id),
        CHECK (history_type IN ('入庫', '出庫')),
        CHECK (qty >= 0),
        CHECK (before_qty >= 0),
        CHECK (after_qty >= 0)
    )
    """,
)


SQLITE_CREATE_STATEMENTS = (
    """
    CREATE TABLE pallet_inventory (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        pallet_code TEXT NOT NULL UNIQUE,
        batch_code TEXT NOT NULL,
        pallet_sequence INTEGER NOT NULL,
        total_pallets INTEGER NOT NULL,
        company_id INTEGER NOT NULL,
        project_id INTEGER,
        item_id INTEGER NOT NULL,
        initial_qty INTEGER NOT NULL,
        current_qty INTEGER NOT NULL,
        status TEXT NOT NULL DEFAULT '保管中',
        location TEXT,
        remarks TEXT,
        created_by TEXT NOT NULL,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        is_deleted INTEGER NOT NULL DEFAULT 0,
        FOREIGN KEY (company_id) REFERENCES companies(id),
        FOREIGN KEY (project_id) REFERENCES projects(id),
        FOREIGN KEY (item_id) REFERENCES items(id),
        UNIQUE (batch_code, pallet_sequence),
        CHECK (pallet_sequence >= 1),
        CHECK (total_pallets >= 1),
        CHECK (pallet_sequence <= total_pallets),
        CHECK (initial_qty >= 0),
        CHECK (current_qty >= 0),
        CHECK (current_qty <= initial_qty),
        CHECK (status IN ('保管中', '出庫済み'))
    )
    """,
    """
    CREATE TABLE pallet_history (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        pallet_id INTEGER NOT NULL,
        pallet_code TEXT NOT NULL,
        history_type TEXT NOT NULL,
        qty INTEGER NOT NULL,
        before_qty INTEGER NOT NULL,
        after_qty INTEGER NOT NULL,
        username TEXT NOT NULL,
        remarks TEXT,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (pallet_id) REFERENCES pallet_inventory(id),
        CHECK (history_type IN ('入庫', '出庫')),
        CHECK (qty >= 0),
        CHECK (before_qty >= 0),
        CHECK (after_qty >= 0)
    )
    """,
)


INDEX_STATEMENTS = (
    """
    CREATE INDEX idx_pallet_inventory_batch_code
    ON pallet_inventory (batch_code)
    """,
    """
    CREATE INDEX idx_pallet_inventory_item_status
    ON pallet_inventory (item_id, status)
    """,
    """
    CREATE INDEX idx_pallet_inventory_company
    ON pallet_inventory (company_id)
    """,
    """
    CREATE INDEX idx_pallet_history_pallet_created
    ON pallet_history (pallet_id, created_at)
    """,
)


def row_value(row, key, index=0, default=None):
    if row is None:
        return default

    try:
        return row[key]
    except (KeyError, IndexError, TypeError):
        pass

    try:
        return row[index]
    except (KeyError, IndexError, TypeError):
        return default


def rollback_safely(conn):
    candidates = [conn]
    seen = set()

    while candidates:
        candidate = candidates.pop(0)
        candidate_id = id(candidate)

        if candidate_id in seen:
            continue

        seen.add(candidate_id)
        rollback = getattr(candidate, "rollback", None)

        if callable(rollback):
            try:
                rollback()
            except Exception:
                pass
            return

        for attribute in CONNECTION_ATTRIBUTES:
            try:
                wrapped = getattr(candidate, attribute)
            except (AttributeError, TypeError):
                continue

            if wrapped is not None and wrapped is not candidate:
                candidates.append(wrapped)

    try:
        conn.execute("ROLLBACK")
    except Exception:
        pass


def table_exists(conn, table_name, postgres):
    if postgres:
        cursor = conn.execute(
            """
            SELECT COUNT(*) AS table_count
            FROM information_schema.tables
            WHERE
                table_schema = CURRENT_SCHEMA()
                AND table_name = %s
            """,
            (table_name,),
        )
    else:
        cursor = conn.execute(
            """
            SELECT COUNT(*) AS table_count
            FROM sqlite_master
            WHERE type = 'table' AND name = ?
            """,
            (table_name,),
        )

    row = cursor.fetchone()
    return int(row_value(row, "table_count", 0, 0) or 0) == 1


def table_count(conn, table_name, postgres):
    if not table_exists(conn, table_name, postgres):
        return 0

    cursor = conn.execute(f"SELECT COUNT(*) AS row_count FROM {table_name}")
    row = cursor.fetchone()
    return int(row_value(row, "row_count", 0, 0) or 0)


def rebuild():
    conn = get_connection()
    postgres = is_postgres_connection(conn)
    database_name = "PostgreSQL / Supabase" if postgres else "SQLite"

    try:
        counts = {
            table_name: table_count(conn, table_name, postgres)
            for table_name in TABLES
        }

        print(f"対象DB: {database_name}")
        print(
            "現在件数: "
            f"pallet_inventory={counts['pallet_inventory']}, "
            f"pallet_history={counts['pallet_history']}"
        )

        if any(counts.values()):
            raise RuntimeError(
                "パレットデータが存在するため再構築を中止しました。"
                "データは一切変更されていません。"
            )

        conn.execute("DROP TABLE IF EXISTS pallet_history")
        conn.execute("DROP TABLE IF EXISTS pallet_inventory")

        if postgres:
            conn.execute(
                "DROP SEQUENCE IF EXISTS pallet_history_id_seq"
            )
            conn.execute(
                "DROP SEQUENCE IF EXISTS pallet_inventory_id_seq"
            )
            create_statements = POSTGRES_CREATE_STATEMENTS
        else:
            create_statements = SQLITE_CREATE_STATEMENTS

        for statement in create_statements:
            conn.execute(statement)

        for statement in INDEX_STATEMENTS:
            conn.execute(statement)

        validate_pallet_database(conn)
        conn.commit()

        print("パレット用テーブルの再構築が完了しました。")
        print("ID型・自動採番・外部キー・削除フラグ：確認OK")

    except Exception:
        rollback_safely(conn)
        raise

    finally:
        conn.close()


if __name__ == "__main__":
    rebuild()
